const typography = {
  FONT_FAMILY: "Noto Sans KR",
  LOGOTYPE_FONT_FAMILY: "Montserrat",
  LOGOTYPE_LETTER_SPACING: "-0.04em",
  LOGOTYPE_LARGE_FONT_SIZE: "56px",
  LOGOTYPE_LARGE_LINE_HEIGHT: "72px",
  LOGOTYPE_MEDIUM_FONT_WEIGHT: "500",
  LOGOTYPE_MEDIUM_FONT_SIZE: "32px",
  LOGOTYPE_MEDIUM_LINE_HEIGHT: "40px",
  DISPLAY_FONT_SIZE: "32px",
  DISPLAY_LINE_HEIGHT: "48px",
  LARGE_TEMPLATE_FONT_SIZE: "24px",
  LARGE_TEMPLATE_LINE_HEIGHT: "40px",
  MEDIUM_TEMPLATE_FONT_SIZE: "18px",
  MEDIUM_TEMPLATE_LINE_HEIGHT: "32px",
  SMALL_TEMPLATE_FONT_SIZE: "16px",
  SMALL_TEMPLATE_LINE_HEIGHT: "28px",
  X_SMALL_TEMPLATE_FONT_SIZE: "12px",
  X_SMALL_TEMPLATE_LINE_HEIGHT: "20px",
};

export default typography;
